import type { Metadata } from "next";
import "./globals.css";
import styles from "./layout.module.css";
import { Body, Header, Sidebar, Footer } from "./(components)";
import { MenuLoader } from "@/components/MenuLoader/MenuLoader";
import {notoSans} from "@/font/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${notoSans.variable}`}>
        <div className={styles.wrapper}>
          <Header className={styles.header}/>
          <Sidebar className={styles.sidebar}>
            <MenuLoader/>
          </Sidebar>
          <Body className={styles.body}>
            {children}
          </Body>
          <Footer className={styles.footer}/>
        </div>
      </body>
    </html>
  );
}
