import type { Metadata } from "next";
import "./globals.css";
import styles from "./layout.module.css";
import { Body, Header, Sidebar, Footer } from "./(components)";
import {notoSans} from "@/font/font";
import { Menu, Up } from "@/components";
import { getMenu } from "@/api/menu";
import { TopLevelCategory } from "@/interfaces/page.interface";
import { MenuItem } from "@/interfaces/menu.interface";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const menuDataResults = await Promise.allSettled([
    getMenu(TopLevelCategory.Courses), 
    getMenu(TopLevelCategory.Services),
    getMenu(TopLevelCategory.Books),
    getMenu(TopLevelCategory.Products)
  ]);

  const menuData: MenuItem[][] = menuDataResults.map(dataItem => {
    if(dataItem.status === "fulfilled") {
      return dataItem.value;
    }
    return [];
  });

  return (
    <html lang="ru">
      <body className={`${notoSans.variable}`}>
        <div className={styles.wrapper}>
          <Header className={styles.header} menuData={menuData} />
          <Sidebar className={styles.sidebar}>
            <Menu menuData={menuData}/>
          </Sidebar>
          <Body className={styles.body}>
            {children}
          </Body>
          <Footer className={styles.footer}/>
          <Up/>
        </div>
      </body>
    </html>
  );
}
